params:
  defaultTheme: dark
  homeInfoParams:
    Title: Astronauts' Favorite Key on the Keyboard
    Content: Credit to Hanchen Li and his AI tools.

  socialIcons: # optional
    - name: "GitHub"
      url: "https://github.com/Hanchenli"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/hanchen-space/"
    - name: "Twitter"
      url: "https://twitter.com/hanchen_space"
    - name: "Instagram"
      url: "https://www.instagram.com/hanchen_space/"
    - name: "Facebook"
      url: "https://www.facebook.com/hanchen_space/"

googleAnalytics: "G-JEDR6E5EV4"
